# -*- coding: utf-8 -*-
"""
project_initializer

Project scaffolding helpers for the init CLI command.

Version:0.1.0
Author: Timur Kady
Email: timurkady@yandex.com
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable

from .reporting import CreationReport


class PackageInitializer:
    """Create ``__init__`` markers for project package directories."""

    def __init__(self, package_directories: Iterable[str]) -> None:
        """Remember target directories requiring package initialization."""

        self._package_directories = tuple(package_directories)

    def ensure_packages(self, project_root: Path, report: CreationReport) -> None:
        """Create empty ``__init__.py`` files for configured directories."""

        for directory in self._package_directories:
            package_path = project_root / directory / "__init__.py"
            if package_path.exists():
                report.add_skipped(package_path)
                continue
            package_path.write_text("", encoding="utf-8")
            report.add_created(package_path)


class ConfigTemplateProvider:
    """Generate configuration file templates for project scaffolding."""

    def __init__(self, project_name: str) -> None:
        """Remember the target project name for template rendering."""
        self._project_name = project_name

    def templates(self) -> Dict[str, str]:
        """Return all available configuration templates keyed by filename."""
        return {
            "main.py": self._main_template().format(project_name=self._project_name),
            "orm.py": self._orm_template().format(project_name=self._project_name),
            "settings.py": self._settings_template().format(project_name=self._project_name),
        }

    def _main_template(self) -> str:
        return '''# -*- coding: utf-8 -*-
"""
Application bootstrap for {project_name}.
"""

from __future__ import annotations

from fastapi import FastAPI


class ApplicationFactory:
    """Create FastAPI applications for the project."""

    def build(self) -> FastAPI:
        """Return a FastAPI instance with default metadata."""
        return FastAPI(title="{project_name} administration")


app = ApplicationFactory().build()


# The End

'''

    def _orm_template(self) -> str:
        return '''# -*- coding: utf-8 -*-
"""
Database configuration entry point for {project_name}.
"""

from __future__ import annotations

from typing import Dict


class ORMSettings:
    """Provide placeholder ORM configuration values."""

    def template(self) -> Dict[str, str]:
        """Return a dictionary with example ORM configuration."""
        return {{"default": "sqlite:///db.sqlite3"}}


# The End

'''

    def _settings_template(self) -> str:
        return '''# -*- coding: utf-8 -*-
"""
Primary configuration object for {project_name}.
"""

from __future__ import annotations

from pydantic import BaseSettings


class ProjectSettings(BaseSettings):
    """Basic settings model for the generated project."""

    debug: bool = True
    database_url: str = "sqlite:///db.sqlite3"


settings = ProjectSettings()


# The End

'''


class ProjectInitializer:
    """Build the base filesystem layout for a Freeadmin project."""

    _DIRECTORIES = (
        "config",
        "apps",
        "pages",
        "static",
        "templates",
    )

    _PACKAGE_DIRECTORIES = (
        "config",
        "apps",
    )

    _README_TEMPLATE = """# {project_name}\n\nThis project was generated by the freeadmin CLI utility. Customize the configuration in the `config/` directory.\n"""

    def __init__(self, base_path: Path | None = None) -> None:
        """Prepare the initializer with the filesystem base path."""
        self._base_path = base_path or Path.cwd()
        self._package_initializer = PackageInitializer(self._PACKAGE_DIRECTORIES)

    def create_project(self, project_name: str) -> CreationReport:
        """Create or update the project skeleton under the base path."""
        project_root = self._base_path / project_name
        report = CreationReport(project_root)

        if project_root.exists():
            report.add_skipped(project_root)
        else:
            project_root.mkdir(parents=True, exist_ok=True)
            report.add_created(project_root)

        for directory in self._DIRECTORIES:
            directory_path = project_root / directory
            if directory_path.exists():
                report.add_skipped(directory_path)
                continue
            directory_path.mkdir(parents=True, exist_ok=True)
            report.add_created(directory_path)

        self._package_initializer.ensure_packages(project_root, report)
        self._create_config_files(project_root, report, project_name)
        self._create_readme(project_root, report, project_name)
        return report

    def _create_config_files(
        self,
        project_root: Path,
        report: CreationReport,
        project_name: str,
    ) -> None:
        config_dir = project_root / "config"
        templates = ConfigTemplateProvider(project_name).templates()
        for file_name, template in templates.items():
            file_path = config_dir / file_name
            if file_path.exists():
                report.add_skipped(file_path)
                continue
            file_path.write_text(
                template,
                encoding="utf-8",
            )
            report.add_created(file_path)

    def _create_readme(
        self,
        project_root: Path,
        report: CreationReport,
        project_name: str,
    ) -> None:
        readme_path = project_root / "README.md"
        if readme_path.exists():
            report.add_skipped(readme_path)
            return
        readme_path.write_text(
            self._README_TEMPLATE.format(project_name=project_name),
            encoding="utf-8",
        )
        report.add_created(readme_path)


# The End

